"""ReviewAgent — checks that the narration is grounded in the source slide.

Lightweight LLM call returning a binary verdict (``grounded`` true/false).
If not grounded, the graph re-routes back to the Narrator with the
reviewer's feedback (max 1 retry — operational bound on latency).

# Why binary, no score

The previous version used a continuous score and a 0.6 threshold to
decide retry. That threshold had no empirical or theoretical
justification — picking 0.6 vs 0.7 vs 0.5 produced different behaviour
without any measurement showing which was right. Binary keeps the
contract honest: the LLM either thinks the narration is grounded or it
doesn't, and we act on that single bit.
"""
from __future__ import annotations

import json
import logging
import time
from typing import Any

from agentic.schemas import ReviewResult
from agentic.state import TutorState

log = logging.getLogger("agentic.teaching.reviewer")


# Operational only — bounds on latency. Not a research claim.
MAX_RETRIES = 1


_REVIEW_PROMPT_FR = """Tu es un examinateur strict. Tu reçois une narration générée par un professeur virtuel, le contenu source de la slide, et des extraits de cours pertinents (RAG).

Évalue la narration sur 2 critères :
1. ANCRAGE : la narration ne dit RIEN qui n'est ni dans la source ni dans les extraits RAG (pas d'hallucination)
2. COUVERTURE : la narration mentionne tous les concepts importants de la source

Réponds UNIQUEMENT en JSON strict, sans markdown :
{{"grounded": true|false, "feedback": "...court..."}}

SOURCE (slide) :
{slide_content}

EXTRAITS RAG (sources additionnelles légitimes) :
{rag_chunks}

NARRATION :
{narration}
"""


_REVIEW_PROMPT_EN = """You are a strict reviewer. You receive a narration generated by a virtual professor, the source slide content, and relevant course extracts (RAG).

Evaluate the narration on 2 criteria:
1. GROUNDEDNESS: the narration says NOTHING outside the source AND the RAG extracts (no hallucination)
2. COVERAGE: the narration mentions all the important concepts from the source

Reply STRICT JSON ONLY, no markdown:
{{"grounded": true|false, "feedback": "...short..."}}

SOURCE (slide):
{slide_content}

RAG EXTRACTS (additional legitimate sources):
{rag_chunks}

NARRATION:
{narration}
"""


def _format_chunks_for_review(chunks: list[dict[str, Any]] | None, max_chars: int = 1500) -> str:
    """Concat top-K chunks into a compact source block for the reviewer."""
    if not chunks:
        return "(aucun)"
    out: list[str] = []
    budget = max_chars
    for ch in chunks[:4]:
        content = (ch.get("content") or "").strip()
        if not content:
            continue
        snippet = content[:max(0, budget)]
        if not snippet:
            break
        out.append(f"— {snippet}".strip())
        budget -= len(snippet) + 8
        if budget <= 0:
            break
    return "\n".join(out) if out else "(aucun)"


def _extract_json(raw: str) -> dict[str, Any] | None:
    if not raw:
        return None
    cleaned = raw.strip().replace("```json", "").replace("```", "").strip()
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start == -1 or end <= start:
        return None
    try:
        return json.loads(cleaned[start : end + 1])
    except json.JSONDecodeError:
        return None


class ReviewAgent:
    """Verifies that the Narrator's output is grounded in source + RAG."""

    def __init__(self, brain) -> None:
        self.brain = brain

    def __call__(self, state: TutorState) -> dict[str, Any]:
        start = time.time()
        narration = (state.get("answer") or "").strip()
        slide = (state.get("last_slide_content") or "").strip()
        lang = (state.get("language") or "fr")[:2]

        # Fast paths
        if not narration:
            return {
                "review": ReviewResult(grounded=False, score=0.0, feedback="empty narration"),
                "timings": {**state.get("timings", {}), "review": 0.0},
            }
        if not slide:
            return {
                "review": ReviewResult(grounded=True, score=1.0, feedback="no source to verify"),
                "timings": {**state.get("timings", {}), "review": round(time.time() - start, 3)},
            }

        chunks = state.get("retrieved_chunks") or []
        template = _REVIEW_PROMPT_FR if lang == "fr" else _REVIEW_PROMPT_EN
        prompt = template.format(
            slide_content=slide[:1500],
            rag_chunks=_format_chunks_for_review(chunks),
            narration=narration[:1500],
        )

        try:
            raw, _ = self.brain.ask(prompt, reply_language=lang)
        except Exception as exc:
            log.warning("review LLM call failed: %s — defaulting to PASS", exc)
            return {
                "review": ReviewResult(grounded=True, score=1.0, feedback=f"reviewer unavailable: {exc}"),
                "timings": {**state.get("timings", {}), "review": round(time.time() - start, 3)},
            }

        payload = _extract_json(raw)
        if not payload:
            log.warning("review: invalid JSON, defaulting to PASS. raw=%r", (raw or "")[:120])
            return {
                "review": ReviewResult(grounded=True, score=1.0, feedback="reviewer parse failed"),
                "timings": {**state.get("timings", {}), "review": round(time.time() - start, 3)},
            }

        grounded = bool(payload.get("grounded", True))
        feedback = str(payload.get("feedback", "")).strip()[:240]

        log.info(
            "🔍 teaching reviewer VERDICT | grounded=%s | feedback=%r",
            grounded, feedback[:120],
        )
        return {
            # `score` field kept on ReviewResult for back-compat with the
            # schema, but binarised: 1.0 if grounded, 0.0 otherwise.
            "review": ReviewResult(grounded=grounded, score=1.0 if grounded else 0.0, feedback=feedback),
            "timings": {**state.get("timings", {}), "review": round(time.time() - start, 3)},
        }


def review_router(state: TutorState) -> str:
    """Conditional edge: ``"end"`` (grounded), ``"retry"`` (retry the
    narrator with reviewer feedback), or ``"fallback"`` (retry budget
    exhausted, hand off to the safe-by-construction FallbackNarrator).

    No score threshold — the verdict is binary. The retry budget is
    capped by MAX_RETRIES. Routing to ``"fallback"`` instead of silently
    accepting an ungrounded narration is what gives the graph an honest
    failure mode (Asai et al. 2023 self-reflection pattern: the system
    must be able to say "I don't know how to answer this" rather than
    pretend).
    """
    review = state.get("review")
    retries = state.get("narrator_retries", 0)

    if review is None or not isinstance(review, ReviewResult):
        return "end"
    if review.grounded:
        return "end"
    if retries >= MAX_RETRIES:
        log.info("review: max retries reached, routing to fallback narrator")
        return "fallback"

    log.info("review: not grounded → retry narrator (#%d)", retries + 1)
    return "retry"
